### ISSUE TITLE
Undefined case

### ISSUE THREAD

**Issue by mloubout** [ChevronETC/Jets.jl#20]
`jacobian!` is not defined for `jopAdjoint`. This line

https://github.com/ChevronETC/Jets.jl/blob/620b038f37ea8b1e4c2f198ac79e9ab8961fa724/src/Jets.jl#L356

should be 
```
jacobian!(A::Union{JopLn, jopAdjoint, AbstractMatrix}, mₒ::AbstractArray) = A
```

**Comment by samtkaplan** [comment]
Thanks.  Yes, adding support for this case would be great.

**Comment by mloubout** [comment]
Great!
